#!/usr/bin/env bash
# Build the Noren release candidate for aarch64-apple-darwin, reproducibly.
#
# What this script does, in order:
#
#   1. Refuses a dirty tree, so the artifact always corresponds to a named
#      commit (and that commit's short SHA is part of the artifact name).
#   2. Records full toolchain provenance (NFR-008): rustc/cargo versions,
#      installed targets, host OS/arch, SDK, linker, the lockfile digest, and
#      the exact direct dependency graph.
#   3. Builds with `cargo build --release --locked` plus `--remap-path-prefix`
#      flags for the workspace root and the cargo home. Without the remap,
#      rustc embeds absolute source paths in panic-location strings (verified:
#      two clean checkouts in different directories differed in exactly those
#      bytes plus the content-derived LC_UUID), so no build is reproducible
#      without it.
#   4. Packs a deterministic tar.gz (fixed mtime/owner/mode, no gzip
#      timestamp) containing exactly one file: the `noren-app` binary.
#   5. Writes dist/SHA256SUMS covering the tarball, and verifies it with
#      `shasum -c`. Checksums are generated by this script, never by hand.
#
# Determinism contract: two runs from clean trees of the same commit, on the
# same machine, toolchain, and macOS SDK, produce byte-identical artifacts.
# `build.sh --check-repro` verifies that contract end to end by building the
# current HEAD twice in throwaway git worktrees and comparing digests. What is
# NOT claimed: cross-machine or cross-SDK reproducibility is unverified (the
# linker and SDK are part of the build; their outputs are not pinned by this
# repo), and `SOURCE_DATE_EPOCH` is deliberately not set because no timestamp
# embedding was found in the two-run experiment on this machine.
#
# This script deliberately stops before every owner-only action: no tag, no
# GitHub release, no publication, no signing identity, no notarization. The
# binary carries only the linker's automatic ad-hoc signature; see
# docs/release/install-verification-checklist.md for what that means for a
# user on first launch.
#
# Usage:
#   scripts/release/build.sh               build into dist/
#   scripts/release/build.sh --check-repro  build HEAD twice in temp worktrees
#                                          and compare artifacts
set -euo pipefail

VERSION="0.1.0-preview"
TARGET="aarch64-apple-darwin"
BIN_NAME="noren-app"

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd -P)

die() {
    printf 'build.sh: error: %s\n' "$1" >&2
    exit 1
}

log() {
    printf 'build.sh: %s\n' "$1" >&2
}

# --- 0. Refuse pre-set RUSTFLAGS: determinism requires fixed flags. --------
if [ -n "${RUSTFLAGS:-}" ]; then
    die "RUSTFLAGS is set in the environment ('$RUSTFLAGS'). Unset it; this script sets its own."
fi

# --- 1. Clean-tree guard. ---------------------------------------------------
# In a linked git worktree `.git` is a file; in a plain checkout it is a
# directory. Either spelling means "this is a git checkout".
[ -e "$ROOT/.git" ] || die "no .git at $ROOT (run from a git checkout)"
cd "$ROOT"
if [ -n "$(git status --porcelain)" ]; then
    git status --porcelain >&2
    die "working tree is dirty (see above). Commit or stash first: the artifact name embeds HEAD and must not lie."
fi
COMMIT=$(git rev-parse HEAD)
SHORT_SHA=$(git rev-parse --short=7 HEAD)
COMMIT_SUBJECT=$(git log -1 --format='%s' HEAD)
COMMIT_DATE=$(git log -1 --format='%cI' HEAD)
ARTIFACT_STEM="noren-${VERSION}-${SHORT_SHA}-${TARGET}"
DIST="$ROOT/dist"
STAGE_PARENT="$DIST/stage"
STAGE_DIR="$STAGE_PARENT/$ARTIFACT_STEM"
TARBALL="$DIST/$ARTIFACT_STEM.tar.gz"

# --- 2. Provenance (NFR-008). ----------------------------------------------
CARGO_HOME_RESOLVED=${CARGO_HOME:-"$HOME/.cargo"}
mkdir -p "$DIST"
{
    printf 'Noren release candidate build provenance\n'
    printf 'Generated by scripts/release/build.sh; NFR-008 record.\n'
    printf '\n[artifact]\n'
    printf 'version=%s\n' "$VERSION"
    printf 'commit=%s\n' "$COMMIT"
    printf 'commit_subject=%s\n' "$COMMIT_SUBJECT"
    printf 'commit_date=%s\n' "$COMMIT_DATE"
    printf 'target=%s\n' "$TARGET"
    printf '\n[toolchain]\n'
    rustc --version --verbose
    printf 'cargo='
    cargo --version
    printf 'rustup_active_toolchain='
    rustup show active-toolchain || true
    printf 'installed_targets:\n'
    rustup target list --installed | sed 's/^/  /'
    printf '\n[host]\n'
    printf 'uname='
    uname -a
    printf 'arch='
    uname -m
    sw_vers
    printf 'macos_sdk='
    xcrun --show-sdk-version
    printf 'linker='
    cc --version | sed -n '1p'
    printf 'cargo_home=%s\n' "$CARGO_HOME_RESOLVED"
    printf '\n[inputs]\n'
    printf 'cargo_lock_sha256='
    shasum -a 256 Cargo.lock | awk '{print $1}'
    printf 'rustflags=%s\n' "--remap-path-prefix=<workspace>=/noren --remap-path-prefix=<cargo-home>=/cargo-home"
    printf 'source_date_epoch=not-set (no timestamp embedding found in the two-run experiment)\n'
    printf '\n[direct-dependencies]\n'
    printf 'cargo tree --workspace --depth 1 --edges normal --locked:\n'
    cargo tree --workspace --depth 1 --edges normal --locked | sed 's/^/  /'
} >"$DIST/BUILD-PROVENANCE.txt"

# --- 3. Reproducible build. -------------------------------------------------
# The physical (resolved) root is what rustc receives; also remap the symlinked
# spelling when it differs (/var vs /private/var on macOS).
RUSTFLAGS_VALUE="--remap-path-prefix=$ROOT=/noren"
LOGICAL_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
if [ "$LOGICAL_ROOT" != "$ROOT" ]; then
    RUSTFLAGS_VALUE="$RUSTFLAGS_VALUE --remap-path-prefix=$LOGICAL_ROOT=/noren"
fi
RUSTFLAGS_VALUE="$RUSTFLAGS_VALUE --remap-path-prefix=$CARGO_HOME_RESOLVED=/cargo-home"

log "building $BIN_NAME at $SHORT_SHA with path remapping"
RUSTFLAGS="$RUSTFLAGS_VALUE" cargo build --release --locked --target "$TARGET"
BUILT_BIN="$ROOT/target/$TARGET/release/$BIN_NAME"
[ -f "$BUILT_BIN" ] || die "expected binary at $BUILT_BIN after build"
BINARY_SHA=$(shasum -a 256 "$BUILT_BIN" | awk '{print $1}')
printf 'binary_sha256=%s\n' "$BINARY_SHA" >>"$DIST/BUILD-PROVENANCE.txt"

# --- 4. Deterministic tarball. ---------------------------------------------
log "packing deterministic tarball"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
cp "$BUILT_BIN" "$STAGE_DIR/$BIN_NAME"
chmod 755 "$STAGE_DIR/$BIN_NAME"

# python3 (already required by scripts/check_docs.py in CI) gives exact
# control over tar metadata: ustar format (no pax atime/ctime headers),
# mtime 0, uid/gid 0, empty owner names, fixed mode, and a gzip stream with
# no timestamp and no embedded filename.
python3 - "$STAGE_PARENT" "$ARTIFACT_STEM" "$BIN_NAME" "$TARBALL" <<'PY'
import gzip
import sys
import tarfile
from pathlib import Path

stage_parent, stem, bin_name, tarball = sys.argv[1:5]
root = Path(stage_parent) / stem
binary = root / bin_name
info = tarfile.TarInfo(f"{stem}/{bin_name}")
info.size = binary.stat().st_size
info.mtime = 0
info.mode = 0o755
info.type = tarfile.REGTYPE
info.uid = 0
info.gid = 0
info.uname = ""
info.gname = ""
with open(binary, "rb") as src, open(tarball, "wb") as raw:
    with gzip.GzipFile(fileobj=raw, mode="wb", filename="", mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode="w", format=tarfile.USTAR_FORMAT) as tar:
            tar.addfile(info, src)
PY

# --- 5. Script-generated checksums, self-verified. --------------------------
log "generating and verifying SHA256SUMS"
TARBALL_SHA=$(shasum -a 256 "$TARBALL" | awk '{print $1}')
printf '%s  %s\n' "$TARBALL_SHA" "$(basename "$TARBALL")" >"$DIST/SHA256SUMS"
(
    cd "$DIST"
    shasum -a 256 -c SHA256SUMS
)
BINARY_SIZE=$(stat -f%z "$STAGE_DIR/$BIN_NAME")
TARBALL_SIZE=$(stat -f%z "$TARBALL")

# --- 6. Report. -------------------------------------------------------------
log "done"
{
    printf 'ARTIFACT=%s\n' "$TARBALL"
    printf 'ARTIFACT_SHA256=%s\n' "$TARBALL_SHA"
    printf 'ARTIFACT_SIZE_BYTES=%s\n' "$TARBALL_SIZE"
    printf 'BINARY=%s\n' "$STAGE_DIR/$BIN_NAME"
    printf 'BINARY_SHA256=%s\n' "$BINARY_SHA"
    printf 'BINARY_SIZE_BYTES=%s\n' "$BINARY_SIZE"
    printf 'COMMIT=%s\n' "$COMMIT"
} >&2

# --- --check-repro: the artifact above vs two fresh clean-tree builds. ------
# Compares three digests: the artifact just built in this tree, plus one build
# in each of two throwaway git worktrees of HEAD. All three equal means the
# shipped artifact is what a clean tree produces, twice over.
check_repro() {
    if [ -n "${NOREN_BUILD_SH_NESTED:-}" ]; then
        die "--check-repro must run at the top level, not nested"
    fi
    local tmp
    tmp=$(mktemp -d "${TMPDIR:-/tmp}/noren-repro.XXXXXX")
    log "creating two throwaway worktrees of $SHORT_SHA under $tmp"
    git worktree add --detach "$tmp/a" HEAD >/dev/null 2>&1
    git worktree add --detach "$tmp/b" HEAD >/dev/null 2>&1
    local rc=0
    NOREN_BUILD_SH_NESTED=1 "$tmp/a/scripts/release/build.sh" >&2 || rc=1
    if [ "$rc" -eq 0 ]; then
        NOREN_BUILD_SH_NESTED=1 "$tmp/b/scripts/release/build.sh" >&2 || rc=1
    fi
    if [ "$rc" -ne 0 ]; then
        git worktree remove --force "$tmp/a" >/dev/null 2>&1 || true
        git worktree remove --force "$tmp/b" >/dev/null 2>&1 || true
        git worktree prune
        rm -rf "$tmp"
        die "nested build failed; cannot compare"
    fi
    local sha_a sha_b
    sha_a=$(shasum -a 256 "$tmp/a/dist/$ARTIFACT_STEM.tar.gz" | awk '{print $1}')
    sha_b=$(shasum -a 256 "$tmp/b/dist/$ARTIFACT_STEM.tar.gz" | awk '{print $1}')
    git worktree remove --force "$tmp/a" >/dev/null 2>&1 || true
    git worktree remove --force "$tmp/b" >/dev/null 2>&1 || true
    git worktree prune
    rm -rf "$tmp"
    if [ "$sha_a" != "$sha_b" ] || [ "$sha_a" != "$TARBALL_SHA" ]; then
        log "this-tree build: $TARBALL_SHA"
        log "clean-tree A:    $sha_a"
        log "clean-tree B:    $sha_b"
        die "NOT reproducible: clean-tree runs differ from this tree or each other"
    fi
    log "REPRODUCIBLE: this tree and two clean-tree runs all produced tarball sha256 $sha_a"
    return 0
}

if [ "${1:-}" = "--check-repro" ]; then
    check_repro
elif [ -n "${1:-}" ]; then
    die "unknown argument '$1' (only --check-repro is supported)"
fi
